### ISSUE TITLE
Sticky Footer

### ISSUE THREAD

**Issue by CyrilOlanolan** [CyrilOlanolan/MC111_CyrilOlanolan_ProjectBased#1]
When the content is shorter than the viewport, the footer does not stick to the bottom. 

Sample: https://getbootstrap.com/docs/4.0/examples/sticky-footer/

- Footer should stick to the bottom of viewport
- When the content is longer, the footer should stick to the bottom of the page

**Comment by tremor6916** [comment]
tried fixing it using flexbox and changing the position of the footer 
![image](https://user-images.githubusercontent.com/57930384/132013015-46bb409e-e091-46c4-b6d1-412dbb527e89.png)
![image](https://user-images.githubusercontent.com/57930384/132013117-263a230e-656b-40c6-886b-3f721ebd2449.png)
